# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.5
default_acceleration_scaling_factor: 0.5

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_elbow_pitch_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 2.0
  arm_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 2.0
  arm_shoulder_pitch_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 2.0
  arm_wrist_pitch_joint:
    has_velocity_limits: true
    max_velocity: 1.5
    has_acceleration_limits: false
    max_acceleration: 2.0
  gripper_left_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 1.0
    min_position: -0.06  
    max_position: 0.0
  gripper_right_joint:
    has_velocity_limits: true
    max_velocity: 1.0
    has_acceleration_limits: false
    max_acceleration: 1.0
    min_position: -0.06  
    max_position: 0.0
